service: url-shortener

provider:
  name: aws
  runtime: nodejs10.x   # set node.js runtime
  stage: ${opt:stage, 'dev'}
  region: 'ap-northeast-2'
  memorySize: 1024   # set the maximum memory of the Lambdas in Megabytes
  timeout: 10   # the timeout is 10 seconds (default is 6 seconds)
  versionFunctions: false # disable creating new version on new every new deployment
  environment:
    NODE_ENV: ${self:provider.stage}
    DEFAULT_PAGINATION_LIMIT: '10'

  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource: "*"
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

resources:
  Resources:
    urlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: urls-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: longUrl
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: LognUrlIndex
            KeySchema:
              - AttributeName: longUrl
                KeyType: HASH
            Projection:
              ProjectionType: ALL


functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  excludeDevDependencies: false
  exclude:
    - apidoc/**
    - .**

plugins:
  - serverless-offline
  - serverless-prune-plugin
